### ISSUE TITLE
Add a test suite

### ISSUE THREAD

**Issue by treeowl** [treeowl/compact-sequences#1]

**Comment by treeowl** [comment]
@sjakobi, do you think you could help set up the skeleton of this? I can write all the generators and properties I need, but getting Travis and the testing framework set up is not exactly my forte.

**Comment by Lemmih** [comment]
Are you open to using github actions instead of travis ci?

**Comment by treeowl** [comment]
> Are you open to using github actions instead of travis ci?

I don't know anything about GitHub actions. What are the advantages and disadvantages? Last I checked, most Haskell packages were using Travis.

**Comment by Lemmih** [comment]
Advantages: built-in with github and easy to use. Disadvantages: quite new and probably not worth the move if you already have a working Travis script.

I'll submit a PR for a github action that tests several versions of GHC across linux, mac and windows.

**Comment by treeowl** [comment]
Having Someone Else willing to do the setup work is a huge boost for That Person's choice. Thanks!

**Comment by sjakobi** [comment]
> @sjakobi, do you think you could help set up the skeleton of this?

I'll wait for @Lemmih's CI PR first.

**Comment by treeowl** [comment]
@sjakobi thanks! It looks like that's almost done.

**Comment by sjakobi** [comment]
Which testing framework do you want to use, @treeowl?

`containers` and `u-c` use `test-framework`, but that's hardly maintained these days. Fairly close in spirit is `tasty`, and its maintainer offers pretty great support too.

I'm less familiar with `hspec`, but that has a lot of proponents too. See e.g. the discussion in https://github.com/haskell-unordered-containers/unordered-containers/issues/284.

**Comment by treeowl** [comment]
@sjakobi, I don't care very much. I just want to write my generators and tests and have them run, and make sure CI makes noisy noises when they fail.

**Comment by sjakobi** [comment]
@Lemmih was faster again. Thanks, @Lemmih! :)

**Comment by treeowl** [comment]
Done!
